export const blogPreviews = [
  {
    image: 'https://picsum.photos/300/200',
    category: 'Developer\'s Dialogue',
    title: 'The Importance of Collaboration in Software Development',
    summary: 'Collaboration plays a crucial role in software development. It enables teams to work together efficiently and produce high-quality software products. This article explores the benefits of collaboration and provides practical tips for fostering effective teamwork in development projects.',
    date: '2023-06-01',
  },
  {
    image: 'https://picsum.photos/300/200',
    category: 'Career Advice',
    title: 'Building a Successful Career in Tech',
    summary: 'Are you aspiring to build a successful career in the tech industry? This blog post offers valuable insights and practical advice for individuals looking to make their mark in the ever-evolving world of technology.',
    date: '2023-06-05',
  },
  {
    image: 'https://picsum.photos/300/200',
    category: 'Coding Exercises',
    title: 'Test Your Skills with These Challenging Coding Exercises',
    summary: 'Ready to put your coding skills to the test? This collection of challenging coding exercises will help you sharpen your problem-solving abilities and expand your knowledge across various programming languages and paradigms.',
    date: '2023-06-10',
  },
  {
    image: 'https://picsum.photos/300/200',
    category: 'Language Spotlight',
    title: 'Exploring the Power of Python',
    summary: 'Python has gained immense popularity in recent years due to its simplicity and versatility. In this blog post, we delve into the unique features of Python and showcase its capabilities through real-world examples.',
    date: '2023-06-25',
  },
  {
    image: 'https://picsum.photos/300/200',
    category: 'Learning Resources',
    title: '10 Must-Read Books for Every Programmer',
    summary: 'Looking to expand your programming knowledge? Check out this curated list of must-read books that cover a wide range of programming concepts and best practices. Enhance your skills and broaden your understanding of software development with these valuable resources.',
    date: '2023-06-15',
  },
  {
    image: 'https://picsum.photos/300/200',
    category: 'News and Updates',
    title: 'Latest Trends in Web Development',
    summary: 'Stay up-to-date with the latest trends in web development! This blog post highlights the emerging technologies, frameworks, and practices that are shaping the future of web development. Discover what\'s new and explore the possibilities for creating modern, responsive web applications.',
    date: '2023-06-18',
  },
  {
    image: 'https://picsum.photos/300/200',
    category: 'Fun Fact & Trivia',
    title: 'Surprising Facts About Programming Languages',
    summary: 'Did you know that the first high-level programming language was Fortran? Dive into the intriguing world of programming language history and uncover fascinating facts and trivia. From the origins of popular languages to quirky language features, this blog post will entertain and educate!',
    date: '2023-06-20',
  },
  {
    image: 'https://picsum.photos/300/200',
    category: 'Tips & Tricks for Coding',
    title: 'Mastering Git: Essential Tips for Version Control',
    summary: 'Git is a powerful version control system that every developer should master. In this blog post, we share essential tips and tricks for using Git effectively. From branching strategies to resolving merge conflicts, level up your Git skills and streamline your development workflow.',
    date: '2023-06-22',
  },
  {
    image: 'https://picsum.photos/300/200',
    category: 'Project Showcase',
    title: 'Building a Modern E-Commerce Website with React',
    summary: 'In this project showcase, we demonstrate how to build a modern e-commerce website using React. Follow along as we explore best practices for structuring components, managing state, and integrating with backend APIs. Get inspired and kickstart your next e-commerce project!',
    date: '2023-06-24',
  },
  {
    image: 'https://picsum.photos/300/200',
    category: 'Fun Fact & Trivia',
    title: 'The First Computer Bug',
    summary: 'Did you know that the first computer bug was an actual insect? Discover the story behind this famous incident and delve into the early days of computer programming. Learn about the pioneers and the challenges they faced in building the foundations of modern computing.',
    date: '2023-07-01',
  },
  {
    image: 'https://picsum.photos/300/200',
    category: 'Trips & Tricks for Coding',
    title: 'Optimizing Performance in JavaScript',
    summary: 'Performance is a critical aspect of web development. In this blog post, we explore various techniques for optimizing JavaScript code to enhance the performance of your web applications. From minimizing network requests to efficient DOM manipulation, discover the tricks for building lightning-fast websites.',
    date: '2023-07-03',
  },
  {
    image: 'https://picsum.photos/300/200',
    category: 'Fun Fact & Trivia',
    title: 'The First Computer Bug',
    summary: 'Did you know that the first computer bug was an actual insect? Discover the story behind this famous incident and delve into the early days of computer programming. Learn about the pioneers and the challenges they faced in building the foundations of modern computing.',
    date: '2023-07-01',
  },
  {
    image: 'https://picsum.photos/300/200',
    category: 'Trips & Tricks for Coding',
    title: 'Optimizing Performance in JavaScript',
    summary: 'Performance is a critical aspect of web development. In this blog post, we explore various techniques for optimizing JavaScript code to enhance the performance of your web applications. From minimizing network requests to efficient DOM manipulation, discover the tricks for building lightning-fast websites.',
    date: '2023-07-03',
  },
  {
    image: 'https://picsum.photos/300/200',
    category: 'Project Showcase',
    title: 'Creating a Mobile App with React Native',
    summary: 'Want to build cross-platform mobile apps? Learn how to develop mobile applications using React Native. This project showcase walks you through the process of building a feature-rich mobile app with a single codebase. Explore the power of React Native and bring your app ideas to life!',
    date: '2023-07-05',
  },
  {
    image: 'https://picsum.photos/300/200',
    category: 'Career Advice',
    title: 'Navigating the Job Interview Process',
    summary: 'Preparing for a job interview can be overwhelming. This blog post provides practical advice and tips for acing your next job interview. From resume writing to answering common interview questions, gain the confidence and knowledge to impress potential employers and land your dream job.',
    date: '2023-07-07',
  },
  {
    image: 'https://picsum.photos/300/200',
    category: 'Developer\'s Dialogue',
    title: 'The Role of Soft Skills in Software Development',
    summary: 'Technical skills are essential, but soft skills also play a crucial role in software development. Explore the importance of communication, teamwork, and problem-solving abilities in the success of development projects. Enhance your soft skills and become a well-rounded software engineer.',
    date: '2023-07-10',
  },
];