export const countries = [
  {
    name: 'United States',
    code: 'US',
    states: [
      { name: 'Alabama', code: 'AL' },
      { name: 'Alaska', code: 'AK' },
      { name: 'Arizona', code: 'AZ' },
      { name: 'Arkansas', code: 'AR' },
      { name: 'California', code: 'CA' },
      { name: 'Colorado', code: 'CO' },
      { name: 'Connecticut', code: 'CT' },
      { name: 'Delaware', code: 'DE' },
      { name: 'Florida', code: 'FL' },
      { name: 'Georgia', code: 'GA' },
      { name: 'Hawaii', code: 'HI' },
      { name: 'Idaho', code: 'ID' },
      { name: 'Illinois', code: 'IL' },
      { name: 'Indiana', code: 'IN' },
      { name: 'Iowa', code: 'IA' },
      { name: 'Kansas', code: 'KS' },
      { name: 'Kentucky', code: 'KY' },
      { name: 'Louisiana', code: 'LA' },
      { name: 'Maine', code: 'ME' },
      { name: 'Maryland', code: 'MD' },
      { name: 'Massachusetts', code: 'MA' },
      { name: 'Michigan', code: 'MI' },
      { name: 'Minnesota', code: 'MN' },
      { name: 'Mississippi', code: 'MS' },
      { name: 'Missouri', code: 'MO' },
      { name: 'Montana', code: 'MT' },
      { name: 'Nebraska', code: 'NE' },
      { name: 'Nevada', code: 'NV' },
      { name: 'New Hampshire', code: 'NH' },
      { name: 'New Jersey', code: 'NJ' },
      { name: 'New Mexico', code: 'NM' },
      { name: 'New York', code: 'NY' },
      { name: 'North Carolina', code: 'NC' },
      { name: 'North Dakota', code: 'ND' },
      { name: 'Ohio', code: 'OH' },
      { name: 'Oklahoma', code: 'OK' },
      { name: 'Oregon', code: 'OR' },
      { name: 'Pennsylvania', code: 'PA' },
      { name: 'Rhode Island', code: 'RI' },
      { name: 'South Carolina', code: 'SC' },
      { name: 'South Dakota', code: 'SD' },
      { name: 'Tennessee', code: 'TN' },
      { name: 'Texas', code: 'TX' },
      { name: 'Utah', code: 'UT' },
      { name: 'Vermont', code: 'VT' },
      { name: 'Virginia', code: 'VA' },
      { name: 'Washington', code: 'WA' },
      { name: 'West Virginia', code: 'WV' },
      { name: 'Wisconsin', code: 'WI' },
      { name: 'Wyoming', code: 'WY' },
      { name: 'American Samoa', code: 'AS' },
      { name: 'District of Columbia', code: 'DC' },
      { name: 'Federated States of Micronesia', code: 'FM' },
      { name: 'Guam', code: 'GU' },
      { name: 'Marshall Islands', code: 'MH' },
      { name: 'Northern Mariana Islands', code: 'MP' },
      { name: 'Palau', code: 'PW' },
      { name: 'Puerto Rico', code: 'PR' },
      { name: 'Virgin Islands', code: 'VI' },
    ],
  },
  {
    name: 'Canada',
    code: 'CA',
    states: [
      { name: 'Alberta', code: 'AB' },
      { name: 'British Columbia', code: 'BC' },
      { name: 'Manitoba', code: 'MB' },
      { name: 'New Brunswick', code: 'NB' },
      { name: 'Newfoundland and Labrador', code: 'NL' },
      { name: 'Northwest Territories', code: 'NT' },
      { name: 'Nova Scotia', code: 'NS' },
      { name: 'Nunavut', code: 'NU' },
      { name: 'Ontario', code: 'ON' },
      { name: 'Prince Edward Island', code: 'PE' },
      { name: 'Quebec', code: 'QC' },
      { name: 'Saskatchewan', code: 'SK' },
      { name: 'Yukon', code: 'YT' },
    ],
  },
  {
    name: 'United Kingdom',
    code: 'GB',
    states: [
      { name: 'England', code: 'ENG' },
      { name: 'Scotland', code: 'SCO' },
      { name: 'Wales', code: 'WAL' },
      { name: 'Northern Ireland', code: 'NIR' },
      { name: 'Jersey', code: 'JEY' },
      { name: 'Guernsey', code: 'GGY' },
      { name: 'Isle of Man', code: 'IMN' }
    ],
  },
  {
    name: 'Australia',
    code: 'AU',
    states: [
      { name: 'Australian Capital Territory', code: 'ACT' },
      { name: 'New South Wales', code: 'NSW' },
      { name: 'Northern Territory', code: 'NT' },
      { name: 'Queensland', code: 'QLD' },
      { name: 'South Australia', code: 'SA' },
      { name: 'Tasmania', code: 'TAS' },
      { name: 'Victoria', code: 'VIC' },
      { name: 'Western Australia', code: 'WA' }
    ],
  },
  {
    name: 'India',
    code: 'IN',
    states: [
      { name: 'Andaman and Nicobar Islands', code: 'AN' },
      { name: 'Andhra Pradesh', code: 'AP' },
      { name: 'Arunachal Pradesh', code: 'AR' },
      { name: 'Assam', code: 'AS' },
      { name: 'Bihar', code: 'BR' },
      { name: 'Chandigarh', code: 'CH' },
      { name: 'Chhattisgarh', code: 'CT' },
      { name: 'Dadra and Nagar Haveli', code: 'DN' },
      { name: 'Daman and Diu', code: 'DD' },
      { name: 'Delhi', code: 'DL' },
      { name: 'Goa', code: 'GA' },
      { name: 'Gujarat', code: 'GJ' },
      { name: 'Haryana', code: 'HR' },
      { name: 'Himachal Pradesh', code: 'HP' },
      { name: 'Jammu and Kashmir', code: 'JK' },
      { name: 'Jharkhand', code: 'JH' },
      { name: 'Karnataka', code: 'KA' },
      { name: 'Kerala', code: 'KL' },
      { name: 'Ladakh', code: 'LA' },
      { name: 'Lakshadweep', code: 'LD' },
      { name: 'Madhya Pradesh', code: 'MP' },
      { name: 'Maharashtra', code: 'MH' },
      { name: 'Manipur', code: 'MN' },
      { name: 'Meghalaya', code: 'ML' },
      { name: 'Mizoram', code: 'MZ' },
      { name: 'Nagaland', code: 'NL' },
      { name: 'Odisha', code: 'OD' },
      { name: 'Puducherry', code: 'PY' },
      { name: 'Punjab', code: 'PB' },
      { name: 'Rajasthan', code: 'RJ' },
      { name: 'Sikkim', code: 'SK' },
      { name: 'Tamil Nadu', code: 'TN' },
      { name: 'Telangana', code: 'TG' },
      { name: 'Tripura', code: 'TR' },
      { name: 'Uttar Pradesh', code: 'UP' },
      { name: 'Uttarakhand', code: 'UK' },
      { name: 'West Bengal', code: 'WB' }
    ],
  },
  {
    name: 'China',
    code: 'CN',
    states: [
      { name: 'Anhui', code: 'AH' },
      { name: 'Beijing', code: 'BJ' },
      { name: 'Chongqing', code: 'CQ' },
      { name: 'Fujian', code: 'FJ' },
      { name: 'Gansu', code: 'GS' },
      { name: 'Guangdong', code: 'GD' },
      { name: 'Guangxi', code: 'GX' },
      { name: 'Guizhou', code: 'GZ' },
      { name: 'Hainan', code: 'HI' },
      { name: 'Hebei', code: 'HE' },
      { name: 'Heilongjiang', code: 'HL' },
      { name: 'Henan', code: 'HA' },
      { name: 'Hong Kong', code: 'HK' },
      { name: 'Hubei', code: 'HB' },
      { name: 'Hunan', code: 'HN' },
      { name: 'Inner Mongolia', code: 'NM' },
      { name: 'Jiangsu', code: 'JS' },
      { name: 'Jiangxi', code: 'JX' },
      { name: 'Jilin', code: 'JL' },
      { name: 'Liaoning', code: 'LN' },
      { name: 'Macau', code: 'MO' },
      { name: 'Ningxia', code: 'NX' },
      { name: 'Qinghai', code: 'QH' },
      { name: 'Shaanxi', code: 'SN' },
      { name: 'Shandong', code: 'SD' },
      { name: 'Shanghai', code: 'SH' },
      { name: 'Shanxi', code: 'SX' },
      { name: 'Sichuan', code: 'SC' },
      { name: 'Tianjin', code: 'TJ' },
      { name: 'Tibet', code: 'XZ' },
      { name: 'Xinjiang', code: 'XJ' },
      { name: 'Yunnan', code: 'YN' },
      { name: 'Zhejiang', code: 'ZJ' }
    ],
  },
  {
    name: 'Brazil',
    code: 'BR',
    states: [
      { name: 'Acre', code: 'AC' },
      { name: 'Alagoas', code: 'AL' },
      { name: 'Amapá', code: 'AP' },
      { name: 'Amazonas', code: 'AM' },
      { name: 'Bahia', code: 'BA' },
      { name: 'Ceará', code: 'CE' },
      { name: 'Distrito Federal', code: 'DF' },
      { name: 'Espírito Santo', code: 'ES' },
      { name: 'Goiás', code: 'GO' },
      { name: 'Maranhão', code: 'MA' },
      { name: 'Mato Grosso', code: 'MT' },
      { name: 'Mato Grosso do Sul', code: 'MS' },
      { name: 'Minas Gerais', code: 'MG' },
      { name: 'Pará', code: 'PA' },
      { name: 'Paraíba', code: 'PB' },
      { name: 'Paraná', code: 'PR' },
      { name: 'Pernambuco', code: 'PE' },
      { name: 'Piauí', code: 'PI' },
      { name: 'Rio de Janeiro', code: 'RJ' },
      { name: 'Rio Grande do Norte', code: 'RN' },
      { name: 'Rio Grande do Sul', code: 'RS' },
      { name: 'Rondônia', code: 'RO' },
      { name: 'Roraima', code: 'RR' },
      { name: 'Santa Catarina', code: 'SC' },
      { name: 'São Paulo', code: 'SP' },
      { name: 'Sergipe', code: 'SE' },
      { name: 'Tocantins', code: 'TO' }
    ],
  },
  {
    name: 'South Africa',
    code: 'ZA',
    states: [
      { name: 'Eastern Cape', code: 'EC' },
      { name: 'Free State', code: 'FS' },
      { name: 'Gauteng', code: 'GP' },
      { name: 'KwaZulu-Natal', code: 'KZN' },
      { name: 'Limpopo', code: 'LP' },
      { name: 'Mpumalanga', code: 'MP' },
      { name: 'Northern Cape', code: 'NC' },
      { name: 'North West', code: 'NW' },
      { name: 'Western Cape', code: 'WC' }
    ],
  },
  {
    name: 'Nigeria',
    code: 'NG',
    states: [
      { name: 'Abia', code: 'AB' },
      { name: 'Adamawa', code: 'AD' },
      { name: 'Akwa Ibom', code: 'AK' },
      { name: 'Anambra', code: 'AN' },
      { name: 'Bauchi', code: 'BA' },
      { name: 'Bayelsa', code: 'BY' },
      { name: 'Benue', code: 'BE' },
      { name: 'Borno', code: 'BO' },
      { name: 'Cross River', code: 'CR' },
      { name: 'Delta', code: 'DE' },
      { name: 'Ebonyi', code: 'EB' },
      { name: 'Edo', code: 'ED' },
      { name: 'Ekiti', code: 'EK' },
      { name: 'Enugu', code: 'EN' },
      { name: 'Federal Capital Territory', code: 'FC' },
      { name: 'Gombe', code: 'GO' },
      { name: 'Imo', code: 'IM' },
      { name: 'Jigawa', code: 'JI' },
      { name: 'Kaduna', code: 'KD' },
      { name: 'Kano', code: 'KN' },
      { name: 'Katsina', code: 'KT' },
      { name: 'Kebbi', code: 'KE' },
      { name: 'Kogi', code: 'KO' },
      { name: 'Kwara', code: 'KW' },
      { name: 'Lagos', code: 'LA' },
      { name: 'Nasarawa', code: 'NA' },
      { name: 'Niger', code: 'NI' },
      { name: 'Ogun', code: 'OG' },
      { name: 'Ondo', code: 'ON' },
      { name: 'Osun', code: 'OS' },
      { name: 'Oyo', code: 'OY' },
      { name: 'Plateau', code: 'PL' },
      { name: 'Rivers', code: 'RI' },
      { name: 'Sokoto', code: 'SO' },
      { name: 'Taraba', code: 'TA' },
      { name: 'Yobe', code: 'YO' },
      { name: 'Zamfara', code: 'ZA' }
    ],
  },
  {
    name: 'Russia',
    code: 'RU',
    states: [
      { name: 'Republic of Adygea', code: 'AD' },
      { name: 'Republic of Altai', code: 'AL' },
      { name: 'Altai Krai', code: 'ALT' },
      { name: 'Amur Oblast', code: 'AMU' },
      { name: 'Arkhangelsk Oblast', code: 'ARK' },
      { name: 'Astrakhan Oblast', code: 'AST' },
      { name: 'Republic of Bashkortostan', code: 'BA' },
      { name: 'Belgorod Oblast', code: 'BEL' },
      { name: 'Bryansk Oblast', code: 'BRY' },
      { name: 'Republic of Buryatia', code: 'BU' },
      { name: 'Chechen Republic', code: 'CE' },
      { name: 'Chelyabinsk Oblast', code: 'CHE' },
      { name: 'Chukotka Autonomous Okrug', code: 'CHU' },
      { name: 'Chuvash Republic', code: 'CU' },
      { name: 'Republic of Dagestan', code: 'DA' },
      { name: 'Republic of Ingushetia', code: 'IN' },
      { name: 'Irkutsk Oblast', code: 'IRK' },
      { name: 'Ivanovo Oblast', code: 'IVA' },
      { name: 'Jewish Autonomous Oblast', code: 'JEW' },
      { name: 'Kabardino-Balkarian Republic', code: 'KB' },
      { name: 'Kaliningrad Oblast', code: 'KGD' },
      { name: 'Republic of Kalmykia', code: 'KL' },
      { name: 'Kaluga Oblast', code: 'KLU' },
      { name: 'Kamchatka Krai', code: 'KAM' },
      { name: 'Karachay-Cherkess Republic', code: 'KC' },
      { name: 'Republic of Karelia', code: 'KR' },
      { name: 'Kemerovo Oblast', code: 'KEM' },
      { name: 'Khabarovsk Krai', code: 'KHA' },
      { name: 'Republic of Khakassia', code: 'KK' },
      { name: 'Khanty-Mansi Autonomous Okrug', code: 'KHM' },
      { name: 'Kirov Oblast', code: 'KIR' },
      { name: 'Komi Republic', code: 'KO' },
      { name: 'Kostroma Oblast', code: 'KOS' },
      { name: 'Krasnodar Krai', code: 'KDA' },
      { name: 'Krasnoyarsk Krai', code: 'KYA' },
      { name: 'Kurgan Oblast', code: 'KGN' },
      { name: 'Kursk Oblast', code: 'KRS' },
      { name: 'Leningrad Oblast', code: 'LEN' },
      { name: 'Lipetsk Oblast', code: 'LIP' },
      { name: 'Magadan Oblast', code: 'MAG' },
      { name: 'Mari El Republic', code: 'ME' },
      { name: 'Republic of Mordovia', code: 'MO' },
      { name: 'Moscow Oblast', code: 'MOS' },
      { name: 'Moscow', code: 'MOW' },
      { name: 'Murmansk Oblast', code: 'MU' },
      { name: 'Nenets Autonomous Okrug', code: 'NEN' },
      { name: 'Nizhny Novgorod Oblast', code: 'NIZ' },
      { name: 'Novgorod Oblast', code: 'NGR' },
      { name: 'Novosibirsk Oblast', code: 'NVS' },
      { name: 'Omsk Oblast', code: 'OMS' },
      { name: 'Orenburg Oblast', code: 'ORE' },
      { name: 'Oryol Oblast', code: 'ORL' },
      { name: 'Penza Oblast', code: 'PNZ' },
      { name: 'Perm Krai', code: 'PER' },
      { name: 'Primorsky Krai', code: 'PRI' },
      { name: 'Pskov Oblast', code: 'PSK' },
      { name: 'Republic of Crimea', code: 'CRI' },
      { name: 'Rostov Oblast', code: 'ROS' },
      { name: 'Ryazan Oblast', code: 'RYA' },
      { name: 'Saint Petersburg', code: 'SPE' },
      { name: 'Sakha Republic (Yakutia)', code: 'SA' },
      { name: 'Sakhalin Oblast', code: 'SAK' },
      { name: 'Samara Oblast', code: 'SAM' },
      { name: 'Saratov Oblast', code: 'SAR' },
      { name: 'Republic of North Ossetia-Alania', code: 'NO' },
      { name: 'Smolensk Oblast', code: 'SMO' },
      { name: 'Stavropol Krai', code: 'STA' },
      { name: 'Sverdlovsk Oblast', code: 'SVE' },
      { name: 'Tambov Oblast', code: 'TAM' },
      { name: 'Republic of Tatarstan', code: 'TA' },
      { name: 'Tomsk Oblast', code: 'TOM' },
      { name: 'Tula Oblast', code: 'TUL' },
      { name: 'Tuva Republic', code: 'TY' },
      { name: 'Tver Oblast', code: 'TVE' },
      { name: 'Tyumen Oblast', code: 'TYU' },
      { name: 'Udmurt Republic', code: 'UD' },
      { name: 'Ulyanovsk Oblast', code: 'ULY' },
      { name: 'Vladimir Oblast', code: 'VLA' },
      { name: 'Volgograd Oblast', code: 'VGG' },
      { name: 'Vologda Oblast', code: 'VLG' },
      { name: 'Voronezh Oblast', code: 'VOR' },
      { name: 'Yamalo-Nenets Autonomous Okrug', code: 'YAN' },
      { name: 'Yaroslavl Oblast', code: 'YAR' },
      { name: 'Zabaykalsky Krai', code: 'ZAB' }
    ],
  },
  {
    name: 'France', code: 'FR', states: [
      { name: 'Auvergne-Rhône-Alpes', code: 'ARA' },
      { name: 'Bourgogne-Franche-Comté', code: 'BFC' },
      { name: 'Brittany', code: 'BRE' },
      { name: 'Centre-Val de Loire', code: 'CVL' },
      { name: 'Corsica', code: 'COR' },
      { name: 'Grand Est', code: 'GES' },
      { name: 'Hauts-de-France', code: 'HDF' },
      { name: 'Île-de-France', code: 'IDF' },
      { name: 'Normandy', code: 'NOR' },
      { name: 'Nouvelle-Aquitaine', code: 'NAQ' },
      { name: 'Occitanie', code: 'OCC' },
      { name: 'Pays de la Loire', code: 'PDL' },
      { name: 'Provence-Alpes-Côte d\'Azur', code: 'PAC' }
    ],
  },
  {
    name: 'Germany', code: 'DE', states: [
      { name: 'Baden-Württemberg', code: 'BW' },
      { name: 'Bavaria', code: 'BY' },
      { name: 'Berlin', code: 'BE' },
      { name: 'Brandenburg', code: 'BB' },
      { name: 'Bremen', code: 'HB' },
      { name: 'Hamburg', code: 'HH' },
      { name: 'Hesse', code: 'HE' },
      { name: 'Lower Saxony', code: 'NI' },
      { name: 'Mecklenburg-Vorpommern', code: 'MV' },
      { name: 'North Rhine-Westphalia', code: 'NW' },
      { name: 'Rhineland-Palatinate', code: 'RP' },
      { name: 'Saarland', code: 'SL' },
      { name: 'Saxony', code: 'SN' },
      { name: 'Saxony-Anhalt', code: 'ST' },
      { name: 'Schleswig-Holstein', code: 'SH' },
      { name: 'Thuringia', code: 'TH' }
    ],
  },
  {
    name: 'Mexico', code: 'MX', states: [
      { name: 'Aguascalientes', code: 'AGU' },
      { name: 'Baja California', code: 'BCN' },
      { name: 'Baja California Sur', code: 'BCS' },
      { name: 'Campeche', code: 'CAM' },
      { name: 'Chiapas', code: 'CHP' },
      { name: 'Chihuahua', code: 'CHH' },
      { name: 'Coahuila', code: 'COA' },
      { name: 'Colima', code: 'COL' },
      { name: 'Durango', code: 'DUR' },
      { name: 'Guanajuato', code: 'GUA' },
      { name: 'Guerrero', code: 'GRO' },
      { name: 'Hidalgo', code: 'HID' },
      { name: 'Jalisco', code: 'JAL' },
      { name: 'México', code: 'MEX' },
      { name: 'Michoacán', code: 'MIC' },
      { name: 'Morelos', code: 'MOR' },
      { name: 'Nayarit', code: 'NAY' },
      { name: 'Nuevo León', code: 'NLE' },
      { name: 'Oaxaca', code: 'OAX' },
      { name: 'Puebla', code: 'PUE' },
      { name: 'Querétaro', code: 'QUE' },
      { name: 'Quintana Roo', code: 'ROO' },
      { name: 'San Luis Potosí', code: 'SLP' },
      { name: 'Sinaloa', code: 'SIN' },
      { name: 'Sonora', code: 'SON' },
      { name: 'Tabasco', code: 'TAB' },
      { name: 'Tamaulipas', code: 'TAM' },
      { name: 'Tlaxcala', code: 'TLA' },
      { name: 'Veracruz', code: 'VER' },
      { name: 'Yucatán', code: 'YUC' },
      { name: 'Zacatecas', code: 'ZAC' }
    ],
  },
  {
    name: 'Japan', code: 'JP', states: [
      { name: 'Aichi', code: '23' },
      { name: 'Akita', code: '05' },
      { name: 'Aomori', code: '02' },
      { name: 'Chiba', code: '12' },
      { name: 'Ehime', code: '38' },
      { name: 'Fukui', code: '18' },
      { name: 'Fukuoka', code: '40' },
      { name: 'Fukushima', code: '07' },
      { name: 'Gifu', code: '21' },
      { name: 'Gunma', code: '10' },
      { name: 'Hiroshima', code: '34' },
      { name: 'Hokkaido', code: '01' },
      { name: 'Hyogo', code: '28' },
      { name: 'Ibaraki', code: '08' },
      { name: 'Ishikawa', code: '17' },
      { name: 'Iwate', code: '03' },
      { name: 'Kagawa', code: '37' },
      { name: 'Kagoshima', code: '46' },
      { name: 'Kanagawa', code: '14' },
      { name: 'Kochi', code: '39' },
      { name: 'Kumamoto', code: '43' },
      { name: 'Kyoto', code: '26' },
      { name: 'Mie', code: '24' },
      { name: 'Miyagi', code: '04' },
      { name: 'Miyazaki', code: '45' },
      { name: 'Nagano', code: '20' },
      { name: 'Nagasaki', code: '42' },
      { name: 'Nara', code: '29' },
      { name: 'Niigata', code: '15' },
      { name: 'Oita', code: '44' },
      { name: 'Okayama', code: '33' },
      { name: 'Okinawa', code: '47' },
      { name: 'Osaka', code: '27' },
      { name: 'Saga', code: '41' },
      { name: 'Saitama', code: '11' },
      { name: 'Shiga', code: '25' },
      { name: 'Shimane', code: '32' },
      { name: 'Shizuoka', code: '22' },
      { name: 'Tochigi', code: '09' },
      { name: 'Tokushima', code: '36' },
      { name: 'Tokyo', code: '13' },
      { name: 'Tottori', code: '31' },
      { name: 'Toyama', code: '16' },
      { name: 'Wakayama', code: '30' },
      { name: 'Yamagata', code: '06' },
      { name: 'Yamaguchi', code: '35' },
      { name: 'Yamanashi', code: '19' }
    ],
  },
  {
    name: 'New Zealand', code: 'NZ', states: [
      { name: 'Northland', code: 'NL' },
      { name: 'Auckland', code: 'AKL' },
      { name: 'Waikato', code: 'WKO' },
      { name: 'Bay of Plenty', code: 'BOP' },
      { name: 'Gisborne', code: 'GIS' },
      { name: 'Hawke\'s Bay', code: 'HKB' },
      { name: 'Taranaki', code: 'TKI' },
      { name: 'Manawatu-Whanganui', code: 'MWT' },
      { name: 'Wellington', code: 'WGN' },
      { name: 'Tasman', code: 'TAS' },
      { name: 'Nelson', code: 'NSN' },
      { name: 'Marlborough', code: 'MBH' },
      { name: 'West Coast', code: 'WTC' },
      { name: 'Canterbury', code: 'CAN' },
      { name: 'Otago', code: 'OTA' },
      { name: 'Southland', code: 'STL' }
    ],
  },
  {
    name: 'Italy', code: 'IT', states: [
      { name: 'Abruzzo', code: '65' },
      { name: 'Aosta Valley', code: '23' },
      { name: 'Apulia', code: '75' },
      { name: 'Basilicata', code: '77' },
      { name: 'Calabria', code: '78' },
      { name: 'Campania', code: '72' },
      { name: 'Emilia-Romagna', code: '45' },
      { name: 'Friuli-Venezia Giulia', code: '36' },
      { name: 'Lazio', code: '62' },
      { name: 'Liguria', code: '42' },
      { name: 'Lombardy', code: '25' },
      { name: 'Marche', code: '57' },
      { name: 'Molise', code: '67' },
      { name: 'Piedmont', code: '21' },
      { name: 'Sardinia', code: '88' },
      { name: 'Sicily', code: '82' },
      { name: 'Trentino-Alto Adige/Südtirol', code: '32' },
      { name: 'Tuscany', code: '52' },
      { name: 'Umbria', code: '55' },
      { name: 'Veneto', code: '34' }
    ],
  },
  {
    name: 'Spain', code: 'ES', states: [
      { name: 'Andalusia', code: 'AN' },
      { name: 'Aragon', code: 'AR' },
      { name: 'Asturias', code: 'AS' },
      { name: 'Balearic Islands', code: 'IB' },
      { name: 'Basque Country', code: 'PV' },
      { name: 'Canary Islands', code: 'CN' },
      { name: 'Cantabria', code: 'CB' },
      { name: 'Castilla-La Mancha', code: 'CM' },
      { name: 'Castile and León', code: 'CL' },
      { name: 'Catalonia', code: 'CT' },
      { name: 'Extremadura', code: 'EX' },
      { name: 'Galicia', code: 'GA' },
      { name: 'La Rioja', code: 'RI' },
      { name: 'Madrid', code: 'MD' },
      { name: 'Murcia', code: 'MC' },
      { name: 'Navarre', code: 'NC' },
      { name: 'Valencian Community', code: 'VC' }
    ],
  },
  {
    name: 'Switzerland', code: 'CH', states: [
      { name: 'Aargau', code: 'AG' },
      { name: 'Appenzell Ausserrhoden', code: 'AR' },
      { name: 'Appenzell Innerrhoden', code: 'AI' },
      { name: 'Basel-Landschaft', code: 'BL' },
      { name: 'Basel-Stadt', code: 'BS' },
      { name: 'Bern', code: 'BE' },
      { name: 'Fribourg', code: 'FR' },
      { name: 'Geneva', code: 'GE' },
      { name: 'Glarus', code: 'GL' },
      { name: 'Graubünden', code: 'GR' },
      { name: 'Jura', code: 'JU' },
      { name: 'Lucerne', code: 'LU' },
      { name: 'Neuchâtel', code: 'NE' },
      { name: 'Nidwalden', code: 'NW' },
      { name: 'Obwalden', code: 'OW' },
      { name: 'Schaffhausen', code: 'SH' },
      { name: 'Schwyz', code: 'SZ' },
      { name: 'Solothurn', code: 'SO' },
      { name: 'St. Gallen', code: 'SG' },
      { name: 'Thurgau', code: 'TG' },
      { name: 'Ticino', code: 'TI' },
      { name: 'Uri', code: 'UR' },
      { name: 'Valais', code: 'VS' },
      { name: 'Vaud', code: 'VD' },
      { name: 'Zug', code: 'ZG' },
      { name: 'Zurich', code: 'ZH' }
    ],
  },
  {
    name: 'Belgium', code: 'BE', states: [
      { name: 'Brussels', code: 'BRU' },
      { name: 'Flanders', code: 'VLG' },
      { name: 'Wallonia', code: 'WAL' }
    ],
  },
  {
    name: 'Netherlands', code: 'NL', states: [
      { name: 'Drenthe', code: 'DR' },
      { name: 'Flevoland', code: 'FL' },
      { name: 'Friesland', code: 'FR' },
      { name: 'Gelderland', code: 'GE' },
      { name: 'Groningen', code: 'GR' },
      { name: 'Limburg', code: 'LI' },
      { name: 'North Brabant', code: 'NB' },
      { name: 'North Holland', code: 'NH' },
      { name: 'Overijssel', code: 'OV' },
      { name: 'South Holland', code: 'ZH' },
      { name: 'Utrecht', code: 'UT' },
      { name: 'Zeeland', code: 'ZE' }
    ],
  },
  {
    name: 'Other', code: 'OT', states: [
      { name: 'Other', code: 'OT' }
    ]
  },
];
