export const countries = [
  { name: 'United States', code: 'US' },
  { name: 'Canada', code: 'CA' },
  { name: 'United Kingdom', code: 'GB' },
  { name: 'Australia', code: 'AU' },
  { name: 'India', code: 'IN' },
  { name: 'China', code: 'CN' },
  { name: 'Brazil', code: 'BR' },
  { name: 'South Africa', code: 'ZA' },
  { name: 'Nigeria', code: 'NG' },
  { name: 'Russia', code: 'RU' },
  { name: 'France', code: 'FR' },
  { name: 'Germany', code: 'DE' },
  { name: 'Mexico', code: 'MX' },
  { name: 'Japan', code: 'JP' },
  { name: 'New Zealand', code: 'NZ' },
  { name: 'Italy', code: 'IT' },
  { name: 'Spain', code: 'ES' },
  { name: 'Switzerland', code: 'CH' },
  { name: 'Belgium', code: 'BE' },
  { name: 'Netherlands', code: 'NL' },
];
